### ISSUE TITLE
Port extension to Ulauncher 5

### ISSUE THREAD

**Issue by vipau** [noam09/ulauncher-units#2]
Ulauncher 5 (of which development builds are already available) will ship the Python 3 version only. As a result, all extensions have to be ported to Python 3, and also the new Ulauncher Extension API v2.

See [more details here](http://docs.ulauncher.io/en/latest/extensions/migration.html#migrate-from-api-v1-to-v2-0-0)

**Comment by noam09** [comment]
Hey @paualberto, I just updated the relevant JSON files. Want to try it out and see if it works fine on v2 of the API?

**Comment by vipau** [comment]
Seems to work fine on Ulauncher 5.2.0, thanks!
